import { describe, it, expect } from 'vitest';

import {
  generateHeaderTemplate,
  generateFooterTemplate,
  generateSessionHeaderTemplate,
  escapeHtml,
} from '../src/templates';

describe('templates', () => {
  describe('generateHeaderTemplate', () => {
    it('should generate header with default title and date', () => {
      const result = generateHeaderTemplate();
      expect(result).toContain('Agent Profiler Report');
      expect(result).toMatch(/\d{4}-\d{2}-\d{2}/);
    });

    it('should use custom title when provided', () => {
      const result = generateHeaderTemplate({ title: 'My Custom Report' });
      expect(result).toContain('My Custom Report');
    });

    it('should use custom date when provided', () => {
      const result = generateHeaderTemplate({ date: '2025-01-15' });
      expect(result).toContain('2025-01-15');
    });

    it('should escape HTML in title', () => {
      const result = generateHeaderTemplate({ title: '<script>alert("xss")</script>' });
      expect(result).toContain('&lt;script&gt;');
      expect(result).not.toContain('<script>');
    });
  });

  describe('generateFooterTemplate', () => {
    it('should include page number placeholders', () => {
      const result = generateFooterTemplate();
      expect(result).toContain('class="pageNumber"');
      expect(result).toContain('class="totalPages"');
    });

    it('should include branding text', () => {
      const result = generateFooterTemplate();
      expect(result).toContain('Generated by Agent Profiler');
    });
  });

  describe('generateSessionHeaderTemplate', () => {
    it('should include session ID in header', () => {
      const result = generateSessionHeaderTemplate('abc-123');
      expect(result).toContain('Session: abc-123');
    });

    it('should use custom title when provided in metadata', () => {
      const result = generateSessionHeaderTemplate('abc-123', { title: 'Custom Title' });
      expect(result).toContain('Custom Title');
    });
  });

  describe('escapeHtml', () => {
    it('should escape angle brackets', () => {
      expect(escapeHtml('<div>')).toBe('&lt;div&gt;');
    });

    it('should escape ampersands', () => {
      expect(escapeHtml('a & b')).toBe('a &amp; b');
    });

    it('should escape quotes', () => {
      expect(escapeHtml('"hello"')).toBe('&quot;hello&quot;');
    });

    it('should escape single quotes', () => {
      expect(escapeHtml("it's")).toBe("it&#039;s");
    });

    it('should handle empty strings', () => {
      expect(escapeHtml('')).toBe('');
    });
  });
});
