/**
 * Escape HTML special characters.
 */
export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export interface HeaderOptions {
  title?: string | undefined;
  date?: string | undefined;
}

/**
 * Generate the header HTML template for Electron printToPDF.
 */
export function generateHeaderTemplate(opts?: HeaderOptions): string {
  const title = opts?.title ?? 'Agent Profiler Report';
  const date = opts?.date ?? new Date().toISOString().split('T')[0]!;
  return `
    <div style="font-size:9px; width:100%; padding:5px 20px; display:flex; justify-content:space-between; color:#555;">
      <span>${escapeHtml(title)}</span>
      <span>${escapeHtml(date)}</span>
    </div>`;
}

/**
 * Generate the footer HTML template for Electron printToPDF.
 */
export function generateFooterTemplate(): string {
  return `
    <div style="font-size:8px; width:100%; padding:5px 20px; display:flex; justify-content:space-between; color:#777;">
      <span>Generated by Agent Profiler</span>
      <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
    </div>`;
}

/**
 * Generate header for session export with session metadata.
 */
export function generateSessionHeaderTemplate(
  sessionId: string,
  metadata?: { title?: string | undefined },
): string {
  const title = metadata?.title ?? `Session: ${sessionId}`;
  return generateHeaderTemplate({ title });
}
